name: ipetv1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  cupertino_icons: ^1.0.1

#https://pub.dev/packages/provider
  provider:
#https://pub.dev/packages/flutter_svg
  flutter_svg:
#https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^4.0.2+3
#https://pub.dev/packages/country_code_picker
  country_code_picker: ^1.7.0
#https://pub.dev/packages/intl_phone_field
  intl_phone_field: ^1.4.2
#https://pub.dev/packages/custom_navigation_bar
  custom_navigation_bar: ^0.7.0
#https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^8.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300